# Configuration file

test_dir: /mnt/sda/clevr-dataset-gen-1/datasets/2views/test
test_pairs_per_scene: 1
num_test_scenes: 250

train_log_dir: ./logs/2views/
checkpoint_path: ./logs/2views/checkpoints
results_dir: ./logs/2views/eval/

batch_size: 5
save_out_first_n: 50
circle_source_img_path: /mnt/sda/clevr-dataset-gen-1/datasets/2views/test/004500/rgb/000000.png /mnt/sda/clevr-dataset-gen-1/datasets/2views/test/004501/rgb/000001.png
