# Configuration file

test_dir: /mnt/sda/clevr-dataset-gen-1/manyviews/scenes/test
test_pairs_per_scene: 300
num_test_scenes: 1

train_log_dir: ./logs/one_scene_nv/
checkpoint_path: ./logs/one_scene_nv/checkpoints
results_dir: ./logs/one_scene_nv/eval/

batch_size: 2
save_out_first_n: 50
circle_source_img_path: /mnt/sda/clevr-dataset-gen-1/manyviews/scenes/test/000000/rgb/000808.png #/mnt/sda/clevr-dataset-gen-1/manyviews/scenes/test/000000/rgb/000803.png /mnt/sda/clevr-dataset-gen-1/manyviews/scenes/test/000000/rgb/000887.png /mnt/sda/clevr-dataset-gen-1/manyviews/scenes/test/000000/rgb/000876.png
