# Configuration file

train_dir: /mnt/sda/clevr-dataset-gen-1/manyviews/scenes/train
val_dir: /mnt/sda/clevr-dataset-gen-1/manyviews/scenes/val
train_pairs_per_scene: 300
num_train_scenes: 1
val_pairs_per_scene: 90
num_val_scenes: 1

batch_size: 2
epochs: 100

name: one_scene