# Configuration file

train_dir: /mnt/datasets/joe/clevr/2views/train
val_dir: /mnt/datasets/joe/clevr/2views/val
train_pairs_per_scene: 1
num_train_scenes: -1
val_pairs_per_scene: 1
num_val_scenes: -1

batch_size: 12
epochs: 2000

name: 2views