# Configuration file

train_dir: /mnt/sda/clevr-dataset-gen-1/datasets/2views/train
val_dir: /mnt/sda/clevr-dataset-gen-1/datasets/2views/val
train_pairs_per_scene: 1
num_train_scenes: -1
val_pairs_per_scene: 1
num_val_scenes: -1

batch_size: 10
epochs: 1000

identity_action: False
residual: True
canonical-rep: True

load_from_checkpoint: False
checkpoint_path: ./logs/2views/checkpoints/epoch_0418_iter_119548.pth

name: test